lib/blogpost_web/router.ex
defmodule BlogpostWeb.Router do
  use BlogpostWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {BlogpostWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BlogpostWeb do
    pipe_through :browser

    # get "/", PageController, :index
    get "/", BlogController, :index
    get "/:id", BlogController, :show

    resources "/admin/posts", PostController
  end

  # Other scopes may use custom stacks.
  # scope "/api", BlogpostWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: BlogpostWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/blogpost/application.ex
defmodule Blogpost.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Blogpost.Repo,
      # Start the Telemetry supervisor
      BlogpostWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Blogpost.PubSub},
      # Start the Endpoint (http/https)
      BlogpostWeb.Endpoint
      # Start a worker by calling: Blogpost.Worker.start_link(arg)
      # {Blogpost.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Blogpost.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    BlogpostWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/blogpost/mailer.ex
defmodule Blogpost.Mailer do
  use Swoosh.Mailer, otp_app: :blogpost
end

lib/blogpost/posts.ex
defmodule Blogpost.Posts do
  @moduledoc """
  The Posts context.
  """

  import Ecto.Query, warn: false
  alias Blogpost.Repo

  alias Blogpost.Posts.Post

  @doc """
  Returns the list of posts.

  ## Examples

      iex> list_posts()
      [%Post{}, ...]

  """
  def list_posts do
    Repo.all(Post)
  end

  @doc """
  Gets a single post.

  Raises `Ecto.NoResultsError` if the Post does not exist.

  ## Examples

      iex> get_post!(123)
      %Post{}

      iex> get_post!(456)
      ** (Ecto.NoResultsError)

  """
  def get_post!(id), do: Repo.get!(Post, id)

  @doc """
  Creates a post.

  ## Examples

      iex> create_post(%{field: value})
      {:ok, %Post{}}

      iex> create_post(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_post(attrs \\ %{}) do
    %Post{}
    |> Post.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a post.

  ## Examples

      iex> update_post(post, %{field: new_value})
      {:ok, %Post{}}

      iex> update_post(post, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_post(%Post{} = post, attrs) do
    post
    |> Post.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a post.

  ## Examples

      iex> delete_post(post)
      {:ok, %Post{}}

      iex> delete_post(post)
      {:error, %Ecto.Changeset{}}

  """
  def delete_post(%Post{} = post) do
    Repo.delete(post)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking post changes.

  ## Examples

      iex> change_post(post)
      %Ecto.Changeset{data: %Post{}}

  """
  def change_post(%Post{} = post, attrs \\ %{}) do
    Post.changeset(post, attrs)
  end
end

lib/blogpost/posts/post.ex
defmodule Blogpost.Posts.Post do
  use Ecto.Schema
  import Ecto.Changeset

  schema "posts" do
    field :author, :string
    field :body, :string
    field :title, :string

    timestamps()
  end

  @doc false
  def changeset(post, attrs) do
    post
    |> cast(attrs, [:title, :body, :author])
    |> validate_required([:title, :body, :author])
  end
end

lib/blogpost/repo.ex
defmodule Blogpost.Repo do
  use Ecto.Repo,
    otp_app: :blogpost,
    adapter: Ecto.Adapters.Postgres
end

lib/blogpost_web/controllers/blog_controller.ex
defmodule BlogpostWeb.BlogController do
  use BlogpostWeb, :controller

  alias Blogpost.Posts

  def index(conn, _params) do
    posts = Posts.list_posts()

    render(conn, "index.html", posts: posts)
  end

  def show(conn, %{"id" => id}) do
    post = Posts.get_post!(id)
    render(conn, "show.html", post: post)
  end
end

lib/blogpost_web/controllers/page_controller.ex
defmodule BlogpostWeb.PageController do
  use BlogpostWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/blogpost_web/controllers/post_controller.ex
defmodule BlogpostWeb.PostController do
  use BlogpostWeb, :controller

  alias Blogpost.Posts
  alias Blogpost.Posts.Post

  def index(conn, _params) do
    posts = Posts.list_posts()
    render(conn, "index.html", posts: posts)
  end

  def new(conn, _params) do
    changeset = Posts.change_post(%Post{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"post" => post_params}) do
    case Posts.create_post(post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post created successfully.")
        |> redirect(to: Routes.post_path(conn, :show, post))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    post = Posts.get_post!(id)
    render(conn, "show.html", post: post)
  end

  def edit(conn, %{"id" => id}) do
    post = Posts.get_post!(id)
    changeset = Posts.change_post(post)
    render(conn, "edit.html", post: post, changeset: changeset)
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
    post = Posts.get_post!(id)

    case Posts.update_post(post, post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post updated successfully.")
        |> redirect(to: Routes.post_path(conn, :show, post))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", post: post, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    post = Posts.get_post!(id)
    {:ok, _post} = Posts.delete_post(post)

    conn
    |> put_flash(:info, "Post deleted successfully.")
    |> redirect(to: Routes.post_path(conn, :index))
  end
end

lib/blogpost_web/views/blog_view.ex
defmodule BlogpostWeb.BlogView do
  use BlogpostWeb, :view
end

lib/blogpost_web/views/error_view.ex
defmodule BlogpostWeb.ErrorView do
  use BlogpostWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/blogpost_web/views/layout_view.ex
defmodule BlogpostWeb.LayoutView do
  use BlogpostWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/blogpost_web/views/page_view.ex
defmodule BlogpostWeb.PageView do
  use BlogpostWeb, :view
end

lib/blogpost_web/views/post_view.ex
defmodule BlogpostWeb.PostView do
  use BlogpostWeb, :view
end

lib/blogpost_web/templates/blog/index.html.heex
<h1>Post list</h1>

<div>
  <%= for post <- @posts do %>
      <div class="post-list">
        <h2><%= link post.title, to: Routes.blog_path(@conn, :show, post) %></h2>

        <div class="post-description">

          <div>
            <span>Autor:</span>
            <strong>
            <span><%= post.author %></span>
            </strong>
          </div>
        </div>
      </div>

  <% end %>
</div>

lib/blogpost_web/templates/blog/show.html.heex
<div class="post-wrapper">
  <h1><%= @post.title %></h1>

  <div>
    <%= @post.body %>
  </div>

  <div class="post-description">
    <div class="">
    <span>Creation date:</span>
      <strong>
        <span><%= @post.inserted_at.day %>-<%= @post.inserted_at.month %>-<%= @post.inserted_at.year %></span>
        <span><%= @post.inserted_at.hour %>:<%= @post.inserted_at.minute %></span>
      </strong>
    </div>
    <div>
      <span>Modification date:</span>
      <strong>
      <span><%= @post.updated_at.day %>-<%= @post.updated_at.month %>-<%= @post.updated_at.year %> </span>
      <span><%= @post.updated_at.hour %>:<%= @post.updated_at.minute %></span>
      </strong>
    </div>
    <div>
      <span>Autor:</span>
      <strong>
      <span><%= @post.author %></span>
      </strong>
    </div>
  </div>

  <span><%= link "Back", to: Routes.blog_path(@conn, :index) %></span>

</div>

lib/blogpost_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/blogpost_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/blogpost_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "Blogpost", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/admin/posts">Admin panel</a></li>
          </ul>
        </nav>
        <h1 class="blog-title">Blog</h1>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>

lib/blogpost_web/templates/page/index.html.heex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>Peace of mind from prototype to production</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.6/CHANGELOG.md">v1.6 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://web.libera.chat/#elixir">#elixir on Libera Chat (IRC)</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
      <li>
        <a href="https://elixir-slackin.herokuapp.com/">Elixir on Slack</a>
      </li>
      <li>
        <a href="https://discord.gg/elixir">Elixir on Discord</a>
      </li>
    </ul>
  </article>
</section>

lib/blogpost_web/templates/post/edit.html.heex
<h1>Edit Post</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.post_path(@conn, :update, @post)) %>

<span><%= link "Back", to: Routes.post_path(@conn, :index) %></span>

lib/blogpost_web/templates/post/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :body %>
  <%= textarea f, :body %>
  <%= error_tag f, :body %>

  <%= label f, :author %>
  <%= text_input f, :author %>
  <%= error_tag f, :author %>

  <div>
    <%= submit "Save" %>
  </div>
</.form>

lib/blogpost_web/templates/post/index.html.heex
<h1>Post list</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Author</th>
      <th>Creation date</th>
      <th>Modification date</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for post <- @posts do %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.body %></td>
      <td><%= post.author %></td>
      <td>
        <span><%= post.inserted_at.day %>-<%= post.inserted_at.month %>-<%= post.inserted_at.year %></span>
        <span><%= post.inserted_at.hour %>:<%= post.inserted_at.minute %></span>
      </td>
      <td>
        <span><%= post.updated_at.day %>-<%= post.updated_at.month %>-<%= post.updated_at.year %> </span>
        <span><%= post.updated_at.hour %>:<%= post.updated_at.minute %></span>
      </td>

      <td>
        <span><%= link "Show", to: Routes.post_path(@conn, :show, post) %></span>
        <span><%= link "Edit", to: Routes.post_path(@conn, :edit, post) %></span>
        <span><%= link "Delete", to: Routes.post_path(@conn, :delete, post), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><strong><%= link "Add Post", to: Routes.post_path(@conn, :new) %></strong></span>

lib/blogpost_web/templates/post/new.html.heex
<h1>Add post</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.post_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.post_path(@conn, :index) %></span>

lib/blogpost_web/templates/post/show.html.heex
<h1>Show post</h1>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @post.title %>
  </li>

  <li>
    <strong>Body:</strong>
    <%= @post.body %>
  </li>

  <li>
    <strong>Author:</strong>
    <%= @post.author %>
  </li>

    <li>
      <strong>Data dodania:</strong>
      <span><%= @post.inserted_at.day %>-<%= @post.inserted_at.month %>-<%= @post.inserted_at.year %></span>
      <span><%= @post.inserted_at.hour %>:<%= @post.inserted_at.minute %></span>
    </li>


    <li>
      <strong>Data modyfikacji:</strong>
      <span><%= @post.updated_at.day %>-<%= @post.updated_at.month %>-<%= @post.updated_at.year %> </span>
      <span><%= @post.updated_at.hour %>:<%= @post.updated_at.minute %></span>
    </li>

</ul>

<span><%= link "Edit", to: Routes.post_path(@conn, :edit, @post) %></span> |
<span><%= link "Back", to: Routes.post_path(@conn, :index) %></span>